library(knitr)
library(dplyr)
library(readr)
library(rvest)
library(gsubfn)
library(ggplot2)
library(reshape2)
library(devtools)
library(tidyr)
library(digest)
library(rgeos)
library(maptools)
library(rmarkdown)
library(DT)
library(extrafont)
library(RSQLite)
library(lubridate)
library(shiny)
library(shinyjs)
library(shinydashboard)
library(shinyFeedback)
library(glue)
library(sodium)
library(sqldf)
library(DBI)
m <-dbDriver("SQLite")
con <- dbConnect(m, dbname = ":memory:")

initExtension(con)  # access extfuns

dbWriteTable(con, 'BOD', BOD, row.names = FALSE)

dbGetQuery(con, 'select variance(demand) from BOD')
##   variance(demand)
## 1         21.44267

dbDisconnect(con)